"""init

Revision ID: 302f4b84149d
Revises: dd33cb03d01f
Create Date: 2023-10-29 05:30:37.851179

"""

# revision identifiers, used by Alembic.
revision = '302f4b84149d'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
