"""init

Revision ID: 46ddd39ca261
Revises: 9d28f696c5a4
Create Date: 2023-10-29 05:38:58.508698

"""

# revision identifiers, used by Alembic.
revision = '46ddd39ca261'
down_revision = '9d28f696c5a4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
