"""init

Revision ID: 4c486d8f89f2
Revises: 302f4b84149d
Create Date: 2023-10-29 05:35:40.335759

"""

# revision identifiers, used by Alembic.
revision = '4c486d8f89f2'
down_revision = '302f4b84149d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
