"""init

Revision ID: 55f87a3ebadd
Revises: af7cc9e3c4ae
Create Date: 2023-10-29 05:59:55.462344

"""

# revision identifiers, used by Alembic.
revision = '55f87a3ebadd'
down_revision = 'af7cc9e3c4ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
