"""init

Revision ID: 6dd69bb6c1e1
Revises: 55f87a3ebadd
Create Date: 2023-10-29 06:01:28.430017

"""

# revision identifiers, used by Alembic.
revision = '6dd69bb6c1e1'
down_revision = '55f87a3ebadd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
