"""init

Revision ID: 9d28f696c5a4
Revises: 4c486d8f89f2
Create Date: 2023-10-29 05:36:23.571266

"""

# revision identifiers, used by Alembic.
revision = '9d28f696c5a4'
down_revision = '4c486d8f89f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
