"""init

Revision ID: 9e86d16be8ac
Revises: 46ddd39ca261
Create Date: 2023-10-29 05:39:43.283356

"""

# revision identifiers, used by Alembic.
revision = '9e86d16be8ac'
down_revision = '46ddd39ca261'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
