"""init

Revision ID: af7cc9e3c4ae
Revises: 9e86d16be8ac
Create Date: 2023-10-29 05:56:17.129099

"""

# revision identifiers, used by Alembic.
revision = 'af7cc9e3c4ae'
down_revision = '9e86d16be8ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
